FROM alpine:3.17.2

USER root
SHELL ["/bin/sh", "-o", "pipefail", "-c"]

ENV USERNAME=root \
    GROUPNAME=root \
    AWS_CLI_VERSION=1.27.85 \
    DEFAULT_TERRAFORM_VERSION=1.3.6 \
    PRECOMMIT_VERSION=3.1.1 \
    TFENV_VERSION=v3.0.0 \
    TFLINT_VERSION=v0.45.0 \
    TFDOCS_VERSION=v0.16.0

#RUN addgroup -g $GROUPID $GROUPNAME && \
#    adduser -D -u $USERID -G $GROUPNAME $USERNAME

WORKDIR /home/root

# bash, curl, git, openssh, pip, awscli
RUN apk -v --no-cache add \
    bash=5.2.15-r0 \
    curl=7.88.1-r0 \
    git=2.38.4-r1 \
    jq=1.6-r2 \
    unzip=6.0-r13 \
#    openssh=7.9_p1-r6 \
#    py2-pip=18.1-r0 && \
    py3-pip=22.3.1-r1 && \
    pip install --upgrade awscli==$AWS_CLI_VERSION && \
    apk -v --purge del py-pip

# tfenv
RUN git clone https://github.com/tfutils/tfenv.git --branch $TFENV_VERSION .tfenv && \
    ln -s /home/root/.tfenv/bin/* /usr/local/bin && \
    chown $USERNAME:$GROUPNAME -R .tfenv && \
    tfenv install $DEFAULT_TERRAFORM_VERSION && \
    tfenv use $DEFAULT_TERRAFORM_VERSION

# pre-commit
RUN pip install --upgrade pre-commit==$PRECOMMIT_VERSION && \
    # tflint
#    curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash && \
    curl -Lo /home/root/tflint.zip https://github.com/terraform-linters/tflint/releases/download/$TFLINT_VERSION/tflint_linux_amd64.zip && \
    unzip /home/root/tflint.zip -d /home/root && \
    mv /home/root/tflint /usr/local/bin/ && rm -r /home/root/tflint.zip && \
    # terraform-docs
    curl -Lo /home/root/terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/$TFDOCS_VERSION/terraform-docs-$TFDOCS_VERSION-linux-amd64.tar.gz && \
    tar -xzf /home/root/terraform-docs.tar.gz -C /home/root/ && \
    mv /home/root/terraform-docs /usr/local/bin/ && rm -r /home/root/terraform-docs.tar.gz && \
    chmod -R +x /usr/local/bin

ENTRYPOINT ["/bin/sh"]
